// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://lceadldzafjhwyknzzwz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZWFkbGR6YWZqaHd5a256end6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI3NzU1NzUsImV4cCI6MjA0ODM1MTU3NX0.G_MKHzWWAGwdyYKdHtCVlZb66WKPOlxC7AS6D3xMoY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);